In [5]:
import pandas as pd
import numpy as np


class MLP:
    
    def f1(self, x):
        tanh = (np.exp(x)-np.exp(-x))/(np.exp(x)+np.exp(-x))
        return tanh

    def f2(self, x):
        return 1/(1 - np.exp(-x))

    def f1_der(self, x):
        tt = (np.exp(x)-np.exp(-x))/(np.exp(x)+np.exp(-x))
        tt = 1-tt**2
        return tt

    def f2_der(self, x):

        return -(np.exp(-x) / ((1 - np.exp(-x)) ** 2))

    def train_neural_nekwork(self, x, y):
        print("x", x)
        print("y", y)
            
        w1 = np.array([[0.1,0.2,0.3],[0.4,0.5,0.6],[0.7,0.8,0.9]])
        w2 = np.array([[0.1, 0.2, 0.3], [0.4, 0.5, 0.6]])

        lr =0.00001

        l1_w1 = []

        for i in range(10000):
            ### As it was not a conventional MLP, I broke the hidden layer in two parts,
            ### that connects to each output repectively.
            batch_size = x.shape[0]
            
            hidden_l = np.dot(x,w1)
            hidden_l = self.f1(hidden_l)
            l_a = np.c_[ np.ones(batch_size), hidden_l[:,:2]]
            l_b = np.c_[ np.ones(batch_size), hidden_l[:,1:]] 

            hidden_a = np.dot(l_a,w2[0].T)
            hidden_b = np.dot(l_b,w2[1].T)
            hidden = np.array([hidden_a,hidden_b]).T

            error = hidden - y
            
            ### To implement the backpropagation correctly, it has to be reversed in same fashion,
            ### going backwards from each of the output seperatly and then joining them together

            d2 = error*self.f2_der(hidden)
          
            upper_deri2 = np.dot(l_a, d2.T[0])
            lower_deri2 = np.dot(l_b, d2.T[1])

            w2[0] = w2[0] - (lr * upper_deri2)
            w2[1] = w2[1] - (lr * lower_deri2)

            d1_1 = self.f1_der(hidden_l)
            d1_2_1 =  d2.T[0] * w2[0][1]
            d1_2_2 =  d2.T[0] * w2[0][2] + d2.T[1] * w2[1][1]
            d1_2_3 =  d2.T[1] * w2[1][2]
            d1_2 = np.array([d1_2_1, d1_2_2, d1_2_3])
            d1 = d1_1 * d1_2.T
            w1 = w1 - (lr * np.dot(x.T, d1))
        
            print(error)
            print()

  
            

o1 = MLP()

x =  np.array([[1, 8, 2],[1, 9, 1],[1, 7, 3]]) #,[9,1],[7,3]
y =  np.array([[5, 5],[1,1],[1,1]]) #,[1,1],[1,1]


o1.train_neural_nekwork(x,y)

x [[1 8 2]
 [1 9 1]
 [1 7 3]]
y [[5 5]
 [1 1]
 [1 1]]
[[-4.40003859 -3.50001038]
 [-0.4000703   0.49998108]
 [-0.40002118  0.4999943 ]]

[[-4.40045925 -3.50003814]
 [-0.40049102  0.4999533 ]
 [-0.40044182  0.49996656]]

[[-4.40088063 -3.5000659 ]
 [-0.40091244  0.49992552]
 [-0.40086318  0.49993882]]

[[-4.40130272 -3.50009365]
 [-0.40133458  0.49989773]
 [-0.40128525  0.49991107]]

[[-4.40172553 -3.50012142]
 [-0.40175744  0.49986995]
 [-0.40170803  0.49988332]]

[[-4.40214906 -3.50014918]
 [-0.40218101  0.49984216]
 [-0.40213154  0.49985557]]

[[-4.40257331 -3.50017694]
 [-0.4026053   0.49981437]
 [-0.40255576  0.49982782]]

[[-4.40299828 -3.50020471]
 [-0.40303032  0.49978658]
 [-0.40298071  0.49980006]]

[[-4.40342398 -3.50023248]
 [-0.40345607  0.49975878]
 [-0.40340639  0.49977231]]

[[-4.40385041 -3.50026025]
 [-0.40388254  0.49973098]
 [-0.40383279  0.49974455]]

[[-4.40427757 -3.50028803]
 [-0.40430975  0.49970318]
 [-0.40425993  0.49971679]]

[[-4.40470547 -3.5003158 ]
 [-0.4